// AUTO-GENERATED by tools/gen_icons.py -do not edit by hand.
#pragma once
#include <lvgl.h>

LV_IMAGE_DECLARE(icon_battery);
LV_IMAGE_DECLARE(icon_coolant);
LV_IMAGE_DECLARE(icon_engine);
LV_IMAGE_DECLARE(icon_fuel);
LV_IMAGE_DECLARE(icon_oil);
LV_IMAGE_DECLARE(icon_needle);

// X-macro: X(json-name, symbol) -expand to build a name->dsc table.
#define ICON_TABLE_ENTRIES \
  X("battery", icon_battery) \
  X("coolant", icon_coolant) \
  X("engine", icon_engine) \
  X("fuel", icon_fuel) \
  X("oil", icon_oil)
