# PlatformIO pre-build script: gzip the web UI sources (web/*) into a C header
# of PROGMEM byte arrays (src/web/assets_gen.h) so the SPA ships inside the
# firmware binary — one artifact, one atomic OTA, no filesystem partition.
#
# The header is regenerated on every build but only rewritten when content
# actually changed, so unchanged builds stay incremental. ASSET_ETAG is a
# content hash served as the HTTP ETag — browser caches self-correct after OTA.
import gzip
import hashlib
import os

Import("env")  # noqa: F821 (SCons construction environment)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
WEB_DIR = os.path.join(PROJECT_DIR, "web")
OUT_PATH = os.path.join(PROJECT_DIR, "src", "web", "assets_gen.h")

ASSETS = [
    # (source file, C identifier, MIME type)
    ("index.html", "ASSET_INDEX_HTML", "text/html"),
    ("app.js",     "ASSET_APP_JS",     "application/javascript"),
    ("style.css",  "ASSET_STYLE_CSS",  "text/css"),
]


def build_header():
    chunks = []
    hasher = hashlib.sha1()
    total_raw = 0
    total_gz = 0

    for fname, ident, mime in ASSETS:
        path = os.path.join(WEB_DIR, fname)
        with open(path, "rb") as f:
            raw = f.read()
        hasher.update(raw)
        gz = gzip.compress(raw, 9)
        total_raw += len(raw)
        total_gz += len(gz)
        body = ",".join(str(b) for b in gz)
        chunks.append(
            f"// {fname}: {len(raw)} bytes -> {len(gz)} gzipped ({mime})\n"
            f"const uint8_t {ident}_GZ[] PROGMEM = {{{body}}};\n"
            f"const size_t  {ident}_GZ_LEN = {len(gz)};\n"
        )

    etag = hasher.hexdigest()[:8]
    header = (
        "// AUTO-GENERATED by tools/build_web.py — DO NOT EDIT.\n"
        "// Edit the sources in web/ instead; this file is rebuilt every build.\n"
        f"// Total: {total_raw} bytes raw -> {total_gz} gzipped.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        f'const char ASSET_ETAG[] = "\\"{etag}\\"";\n\n' + "\n".join(chunks)
    )

    existing = None
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            existing = f.read()
    if existing != header:
        os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
        with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
            f.write(header)
        print(f"[build_web] assets_gen.h regenerated ({total_gz} bytes gzipped, etag {etag})")
    else:
        print(f"[build_web] assets_gen.h up to date (etag {etag})")


build_header()
